name: '   SignoftheTimes'
favicon: null
layout_spectrum: 0.36517917667515576
typography_spectrum: 0.13700720621272922
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.09161436068825424
  lightness: 0.8339655383024365
  saturation: 0.21324865357019007
  rhythmicContrast: 0.9750700250733644
purpose: []
